#!/bin/bash
# ============================================================
#  install-trader-control-ea.sh
#  Installs the pre-compiled TraderControlEA into the followerbot
#  container's MT5 terminal, so the SAME lightweight headless terminal
#  that runs the trading bot also pushes the native MT5 economic
#  calendar (and account data) to TraderControlServer.
#
#  Runs on the HOST (LXC). The followerbot terminal runs in portable mode, so
#  its MQL5 folder lives inside the container; this places the EA and preset
#  there via docker cp/exec. It does NOT restart or interrupt the running bot.
#
#  Idempotent and safe: gated behind TRADERCONTROL_EA_ENABLED and never
#  touches trading state. A one-time manual attach (VNC) is still needed
#  the first time — see docs/TRADER_CONTROL_EA.md.
# ============================================================
set -uo pipefail

DEPLOY_DIR="${DEPLOY_DIR:-/opt/followerbot-deploy}"
BOT_CONFIG_DIR="${BOT_CONFIG_DIR:-/opt/bot-config}"
MT5_DATA_DIR="${MT5_DATA_DIR:-/opt/mt5-data}"
APP_UID=911
APP_GID=911

ENV_FILE="$BOT_CONFIG_DIR/.env"
EA_SOURCE_EX5="$DEPLOY_DIR/ea/TraderControlEA.ex5"

log() { echo "[install-ea] $*"; }

# ---------- read control flags from the bot .env ----------
get_env() {
    # get_env KEY  -> prints the value (last wins), stripped of CR
    [ -f "$ENV_FILE" ] || return 0
    sed -n "s/^$1=//p" "$ENV_FILE" | tail -n 1 | tr -d '\r'
}

ENABLED=$(get_env TRADERCONTROL_EA_ENABLED)
EA_URL=$(get_env TRADERCONTROL_EA_URL)
EA_KEY=$(get_env TRADERCONTROL_EA_KEY)

case "$(printf '%s' "$ENABLED" | tr '[:upper:]' '[:lower:]')" in
    1|true|yes|on) : ;;
    *)
        log "TRADERCONTROL_EA_ENABLED is not true — skipping (nothing installed)."
        exit 0
        ;;
esac

# ---------- preconditions ----------
if [ ! -f "$EA_SOURCE_EX5" ]; then
    log "ERROR: compiled EA not found at $EA_SOURCE_EX5"
    log "       Place the compiled TraderControlEA.ex5 there (only the .ex5 binary;"
    log "       raw .mq5 source must never be committed here), then re-run: bot-cli install-ea"
    exit 1
fi

if [ -z "$EA_URL" ]; then
    log "ERROR: TRADERCONTROL_EA_URL is empty in $ENV_FILE"
    exit 1
fi
if [ -z "$EA_KEY" ]; then
    log "ERROR: TRADERCONTROL_EA_KEY is empty in $ENV_FILE"
    exit 1
fi

# ---------- locate the terminal's MQL5 tree (inside the running container) ----------
# The followerbot terminal runs in PORTABLE mode, so its data folder lives inside
# the container (under an anonymous /config volume), not on a host bind mount.
# Place files via docker, which works regardless of the mount layout.
CONTAINER_NAME="${CONTAINER_NAME:-followerbot}"

if ! docker inspect -f '{{.State.Running}}' "$CONTAINER_NAME" 2>/dev/null | grep -q true; then
    log "ERROR: container '$CONTAINER_NAME' is not running. Start it, then retry."
    exit 1
fi

EXPERTS_DIR=$(docker exec "$CONTAINER_NAME" sh -c \
    'find /config -type d -path "*/MQL5/Experts" 2>/dev/null | head -n 1' | tr -d '\r')
if [ -z "$EXPERTS_DIR" ]; then
    log "ERROR: could not find an MQL5/Experts folder inside '$CONTAINER_NAME'."
    log "       The terminal may still be initializing. Retry shortly."
    exit 1
fi
PRESETS_DIR="${EXPERTS_DIR%/Experts}/Presets"
log "Terminal MQL5 Experts (in container): $EXPERTS_DIR"

docker exec "$CONTAINER_NAME" mkdir -p "$EXPERTS_DIR" "$PRESETS_DIR"

# ---------- install the compiled EA (copied into the container) ----------
docker cp "$EA_SOURCE_EX5" "$CONTAINER_NAME:$EXPERTS_DIR/TraderControlEA.ex5"
log "Installed EA -> (container) $EXPERTS_DIR/TraderControlEA.ex5"

# ---------- generate the preset (.set) from env, copy into the container ----------
# MT5 loads a .set of the same base name when attaching the EA. It carries the
# server URL and API key so nothing is typed by hand. The key stays in the bot
# .env and this container-local preset — never in the repo.
TMP_SET=$(mktemp)
chmod 600 "$TMP_SET"
cat > "$TMP_SET" <<SET
; Auto-generated by install-trader-control-ea.sh — do not edit by hand.
InpServerUrl=$EA_URL
InpApiKey=$EA_KEY
InpPushInterval=15
InpSyncCalendar=true
InpFullHistoryOnStart=false
InpCalendarRefreshSec=3600
InpCalendarPastHours=24
InpCalendarFutureDays=14
SET
docker cp "$TMP_SET" "$CONTAINER_NAME:$PRESETS_DIR/TraderControlEA.set"
rm -f "$TMP_SET"
log "Wrote preset -> (container) $PRESETS_DIR/TraderControlEA.set"

# ---------- ownership/permissions inside the container (user abc=911) ----------
# NOTE: the mkdir above runs as root, so the directories themselves must be
# re-owned too — not just the files. MT5 runs as abc and needs to write here.
docker exec "$CONTAINER_NAME" chown abc:abc \
    "$EXPERTS_DIR" "$PRESETS_DIR" \
    "$EXPERTS_DIR/TraderControlEA.ex5" "$PRESETS_DIR/TraderControlEA.set" 2>/dev/null || true
docker exec "$CONTAINER_NAME" chmod 600 "$PRESETS_DIR/TraderControlEA.set" 2>/dev/null || true

# Remove a stray 1-byte placeholder left by earlier manual attempts; MT5 tries to
# compile anything in Experts/ and it only pollutes the log.
docker exec "$CONTAINER_NAME" sh -c \
    "[ -f '$EXPERTS_DIR/tradercontrol.mq5' ] && [ ! -s '$EXPERTS_DIR/tradercontrol.mq5' ] && rm -f '$EXPERTS_DIR/tradercontrol.mq5'" 2>/dev/null || true

# ---------- generate the MT5 startup config (auto-attach on every launch) ------
# MT5 only persists chart profiles on a GRACEFUL shutdown. This container gets
# SIGKILLed (s6-svwait times out), so a manually attached EA is lost on every
# restart and after every MT5 auto-update. A startup .ini makes the terminal
# re-attach the EA itself at launch, removing the manual step entirely.
#
# Symbol must exist on this broker (VT Markets uses suffixes like XAUUSD-VIPc),
# so default to whatever the terminal last had selected.
# NOTE: MT5 writes its .ini files as UTF-16LE, so plain sed/grep find nothing.
EA_SYMBOL=$(get_env TRADERCONTROL_EA_SYMBOL)
if [ -z "$EA_SYMBOL" ]; then
    EA_SYMBOL=$(docker exec "$CONTAINER_NAME" sh -c \
        'f="/config/.wine/drive_c/Program Files/MetaTrader 5/Config/common.ini"; \
         { iconv -f UTF-16LE -t UTF-8 "$f" 2>/dev/null || cat "$f" 2>/dev/null; } \
         | sed -n "s/^SymbolLast=//p" | tail -n 1' | tr -d '\r')
fi
[ -z "$EA_SYMBOL" ] && EA_SYMBOL="EURUSD"
log "Startup chart symbol: $EA_SYMBOL"

TMP_INI=$(mktemp)
cat > "$TMP_INI" <<INI
; Auto-generated by install-trader-control-ea.sh — do not edit by hand.
; Consumed by terminal64.exe via /config: at launch (see s6/followerbot/run).
; Holds no credentials: MT5 reuses the account already stored in accounts.dat.
[Experts]
AllowLiveTrading=1
Enabled=1
Account=0
Profile=0
[StartUp]
Symbol=$EA_SYMBOL
Period=M1
Expert=TraderControlEA
ExpertParameters=TraderControlEA.set
INI
docker cp "$TMP_INI" "$CONTAINER_NAME:/config/.wine/drive_c/mt5-startup.ini"
rm -f "$TMP_INI"
docker exec "$CONTAINER_NAME" chown abc:abc /config/.wine/drive_c/mt5-startup.ini 2>/dev/null || true
log "Wrote startup config -> (container) C:\\mt5-startup.ini"

log "Done. The EA now re-attaches automatically on every terminal start."
log ""
log "Apply it with:  bot-cli restart"
log "Verify with:    bot-cli ea-status"
log ""
log "Only remaining manual step (once per /config volume, via VNC):"
log "  Tools > Options > Expert Advisors > Allow WebRequest for listed URL, add:"
log "       $EA_URL"
log "  (that one IS persisted, in Config/common.ini)"
