#!/bin/bash
# ============================================================
#  install-trader-control-ea.sh
#  Installs the pre-compiled TraderControlEA into the followerbot
#  container's MT5 terminal, so the SAME lightweight headless terminal
#  that runs the trading bot also pushes the native MT5 economic
#  calendar (and account data) to TraderControlServer.
#
#  Runs on the HOST (LXC). The followerbot terminal runs in portable mode, so
#  its MQL5 folder lives inside the container; this places the EA and preset
#  there via docker cp/exec. It does NOT restart or interrupt the running bot.
#
#  Idempotent and safe: gated behind TRADERCONTROL_EA_ENABLED and never
#  touches trading state. A one-time manual attach (VNC) is still needed
#  the first time — see docs/TRADER_CONTROL_EA.md.
# ============================================================
set -uo pipefail

DEPLOY_DIR="${DEPLOY_DIR:-/opt/followerbot-deploy}"
BOT_CONFIG_DIR="${BOT_CONFIG_DIR:-/opt/bot-config}"
MT5_DATA_DIR="${MT5_DATA_DIR:-/opt/mt5-data}"
APP_UID=911
APP_GID=911

ENV_FILE="$BOT_CONFIG_DIR/.env"
EA_SOURCE_EX5="$DEPLOY_DIR/ea/TraderControlEA.ex5"

log() { echo "[install-ea] $*"; }

# ---------- read control flags from the bot .env ----------
get_env() {
    # get_env KEY  -> prints the value (last wins), stripped of CR
    [ -f "$ENV_FILE" ] || return 0
    sed -n "s/^$1=//p" "$ENV_FILE" | tail -n 1 | tr -d '\r'
}

ENABLED=$(get_env TRADERCONTROL_EA_ENABLED)
EA_URL=$(get_env TRADERCONTROL_EA_URL)
EA_KEY=$(get_env TRADERCONTROL_EA_KEY)

case "$(printf '%s' "$ENABLED" | tr '[:upper:]' '[:lower:]')" in
    1|true|yes|on) : ;;
    *)
        log "TRADERCONTROL_EA_ENABLED is not true — skipping (nothing installed)."
        exit 0
        ;;
esac

# ---------- preconditions ----------
if [ ! -f "$EA_SOURCE_EX5" ]; then
    log "ERROR: compiled EA not found at $EA_SOURCE_EX5"
    log "       Place the compiled TraderControlEA.ex5 there (only the .ex5 binary;"
    log "       raw .mq5 source must never be committed here), then re-run: bot-cli install-ea"
    exit 1
fi

if [ -z "$EA_URL" ]; then
    log "ERROR: TRADERCONTROL_EA_URL is empty in $ENV_FILE"
    exit 1
fi
if [ -z "$EA_KEY" ]; then
    log "ERROR: TRADERCONTROL_EA_KEY is empty in $ENV_FILE"
    exit 1
fi

# ---------- locate the terminal's MQL5 tree (inside the running container) ----------
# The followerbot terminal runs in PORTABLE mode, so its data folder lives inside
# the container (under an anonymous /config volume), not on a host bind mount.
# Place files via docker, which works regardless of the mount layout.
CONTAINER_NAME="${CONTAINER_NAME:-followerbot}"

if ! docker inspect -f '{{.State.Running}}' "$CONTAINER_NAME" 2>/dev/null | grep -q true; then
    log "ERROR: container '$CONTAINER_NAME' is not running. Start it, then retry."
    exit 1
fi

EXPERTS_DIR=$(docker exec "$CONTAINER_NAME" sh -c \
    'find /config -type d -path "*/MQL5/Experts" 2>/dev/null | head -n 1' | tr -d '\r')
if [ -z "$EXPERTS_DIR" ]; then
    log "ERROR: could not find an MQL5/Experts folder inside '$CONTAINER_NAME'."
    log "       The terminal may still be initializing. Retry shortly."
    exit 1
fi
PRESETS_DIR="${EXPERTS_DIR%/Experts}/Presets"
log "Terminal MQL5 Experts (in container): $EXPERTS_DIR"

docker exec "$CONTAINER_NAME" mkdir -p "$EXPERTS_DIR" "$PRESETS_DIR"

# ---------- install the compiled EA (copied into the container) ----------
docker cp "$EA_SOURCE_EX5" "$CONTAINER_NAME:$EXPERTS_DIR/TraderControlEA.ex5"
log "Installed EA -> (container) $EXPERTS_DIR/TraderControlEA.ex5"

# ---------- generate the preset (.set) from env, copy into the container ----------
# MT5 loads a .set of the same base name when attaching the EA. It carries the
# server URL and API key so nothing is typed by hand. The key stays in the bot
# .env and this container-local preset — never in the repo.
TMP_SET=$(mktemp)
chmod 600 "$TMP_SET"
cat > "$TMP_SET" <<SET
; Auto-generated by install-trader-control-ea.sh — do not edit by hand.
InpServerUrl=$EA_URL
InpApiKey=$EA_KEY
InpPushInterval=15
InpSyncCalendar=true
InpFullHistoryOnStart=false
InpCalendarRefreshSec=3600
InpCalendarPastHours=24
InpCalendarFutureDays=14
SET
docker cp "$TMP_SET" "$CONTAINER_NAME:$PRESETS_DIR/TraderControlEA.set"
rm -f "$TMP_SET"
log "Wrote preset -> (container) $PRESETS_DIR/TraderControlEA.set"

# ---------- ownership/permissions inside the container (user abc=911) ----------
docker exec "$CONTAINER_NAME" chown abc:abc \
    "$EXPERTS_DIR/TraderControlEA.ex5" "$PRESETS_DIR/TraderControlEA.set" 2>/dev/null || true
docker exec "$CONTAINER_NAME" chmod 600 "$PRESETS_DIR/TraderControlEA.set" 2>/dev/null || true

log "Done. Remaining one-time steps (via VNC, persist afterwards):"
log "  1. In MT5: Tools > Options > Expert Advisors > Allow WebRequest, add:"
log "       $EA_URL"
log "  2. Drag TraderControlEA onto any chart; in the dialog load preset"
log "       'TraderControlEA', enable 'Allow Algo Trading', click OK."
log "  3. Ensure the AutoTrading toolbar button is green."
log "  These persist in the container's MT5 profile as long as the /config"
log "  volume is kept (re-run 'bot-cli install-ea' after a full container rebuild)."
