#!/bin/bash
# ============================================================
#  install-trader-control-ea.sh
#  Installs the pre-compiled TraderControlEA into the followerbot
#  container's MT5 terminal, so the SAME lightweight headless terminal
#  that runs the trading bot also pushes the native MT5 economic
#  calendar (and account data) to TraderControlServer.
#
#  Runs on the HOST (LXC), not inside the container: the terminal's
#  MetaQuotes data folder is bind-mounted, so we place files directly.
#  No compilation, no docker exec, no interruption of the running bot.
#
#  Idempotent and safe: gated behind TRADERCONTROL_EA_ENABLED and never
#  touches trading state. A one-time manual attach (VNC) is still needed
#  the first time — see docs/TRADER_CONTROL_EA.md.
# ============================================================
set -uo pipefail

DEPLOY_DIR="${DEPLOY_DIR:-/opt/followerbot-deploy}"
BOT_CONFIG_DIR="${BOT_CONFIG_DIR:-/opt/bot-config}"
MT5_DATA_DIR="${MT5_DATA_DIR:-/opt/mt5-data}"
APP_UID=911
APP_GID=911

ENV_FILE="$BOT_CONFIG_DIR/.env"
EA_SOURCE_EX5="$DEPLOY_DIR/ea/TraderControlEA.ex5"

log() { echo "[install-ea] $*"; }

# ---------- read control flags from the bot .env ----------
get_env() {
    # get_env KEY  -> prints the value (last wins), stripped of CR
    [ -f "$ENV_FILE" ] || return 0
    sed -n "s/^$1=//p" "$ENV_FILE" | tail -n 1 | tr -d '\r'
}

ENABLED=$(get_env TRADERCONTROL_EA_ENABLED)
EA_URL=$(get_env TRADERCONTROL_EA_URL)
EA_KEY=$(get_env TRADERCONTROL_EA_KEY)

case "$(printf '%s' "$ENABLED" | tr '[:upper:]' '[:lower:]')" in
    1|true|yes|on) : ;;
    *)
        log "TRADERCONTROL_EA_ENABLED is not true — skipping (nothing installed)."
        exit 0
        ;;
esac

# ---------- preconditions ----------
if [ ! -f "$EA_SOURCE_EX5" ]; then
    log "ERROR: compiled EA not found at $EA_SOURCE_EX5"
    log "       Place the compiled TraderControlEA.ex5 there (only the .ex5 binary;"
    log "       raw .mq5 source must never be committed here), then re-run: bot-cli install-ea"
    exit 1
fi

if [ -z "$EA_URL" ]; then
    log "ERROR: TRADERCONTROL_EA_URL is empty in $ENV_FILE"
    exit 1
fi
if [ -z "$EA_KEY" ]; then
    log "ERROR: TRADERCONTROL_EA_KEY is empty in $ENV_FILE"
    exit 1
fi

# ---------- locate the terminal's MQL5 tree (created after MT5 first run) ----------
# Non-portable MT5 stores data under Terminal/<HEXHASH>/. The folder is
# bind-mounted at $MT5_DATA_DIR, so on the host it is:
#   $MT5_DATA_DIR/Terminal/<HEXHASH>/MQL5
TERMINAL_ROOT="$MT5_DATA_DIR/Terminal"
if [ ! -d "$TERMINAL_ROOT" ]; then
    log "ERROR: $TERMINAL_ROOT does not exist yet."
    log "       Start the container at least once (MT5 must have run) before installing the EA."
    exit 1
fi

# Pick the terminal instance dir that actually has an MQL5 tree. Prefer the
# most recently modified one if several exist.
MQL5_DIR=""
while IFS= read -r cand; do
    if [ -d "$cand/MQL5" ]; then
        MQL5_DIR="$cand/MQL5"
        break
    fi
done < <(find "$TERMINAL_ROOT" -maxdepth 1 -type d -name '[0-9A-Fa-f]*' -exec ls -dt {} + 2>/dev/null)

if [ -z "$MQL5_DIR" ]; then
    log "ERROR: no Terminal/<hash>/MQL5 directory found under $TERMINAL_ROOT."
    log "       The terminal may not have finished initializing. Retry shortly."
    exit 1
fi

EXPERTS_DIR="$MQL5_DIR/Experts"
PRESETS_DIR="$MQL5_DIR/Presets"
mkdir -p "$EXPERTS_DIR" "$PRESETS_DIR"

# ---------- install the compiled EA ----------
install -m 644 "$EA_SOURCE_EX5" "$EXPERTS_DIR/TraderControlEA.ex5"
log "Installed EA -> $EXPERTS_DIR/TraderControlEA.ex5"

# ---------- generate the preset (.set) from env ----------
# MT5 loads a .set of the same base name when attaching the EA. This carries
# the server URL and API key so no value is typed by hand. The key lives only
# in the bot .env and this host-only preset, never in the repo.
PRESET_FILE="$PRESETS_DIR/TraderControlEA.set"
umask 077
cat > "$PRESET_FILE" <<SET
; Auto-generated by install-trader-control-ea.sh — do not edit by hand.
InpServerUrl=$EA_URL
InpApiKey=$EA_KEY
InpPushInterval=15
InpSyncCalendar=true
InpFullHistoryOnStart=false
InpCalendarRefreshSec=3600
InpCalendarPastHours=24
InpCalendarFutureDays=14
SET
umask 022
log "Wrote preset -> $PRESET_FILE (contains the API key; host-only, mode 600)"

# ---------- ownership so the container user (abc=911) can read them ----------
chown "${APP_UID}:${APP_GID}" \
    "$EXPERTS_DIR/TraderControlEA.ex5" "$PRESET_FILE" 2>/dev/null || true
chmod 600 "$PRESET_FILE" 2>/dev/null || true

log "Done. Remaining one-time steps (via VNC, persist afterwards):"
log "  1. In MT5: Tools > Options > Expert Advisors > Allow WebRequest, add:"
log "       $EA_URL"
log "  2. Drag TraderControlEA onto any chart; in the dialog load preset"
log "       'TraderControlEA', enable 'Allow Algo Trading', click OK."
log "  3. Ensure the AutoTrading toolbar button is green."
log "  These persist in the bind-mounted terminal profile across restarts."
